#!/usr/bin/env python3
import argparse
import os
import sys
from workflow_py.utils import bash

sys.path.append(os.environ.get("WORKFLOW_PATH"))

parser = argparse.ArgumentParser(description="checkout and pull a branch to review")
parser.add_argument("branch", nargs="?", type=str, help="branch to checkout")
args = parser.parse_args()

branch = args.branch
print(f"branch '{branch}'")
if not branch:
    branch = input("Branch to checkout and pull: ")
print(f"branch '{branch}'")

bash("git", "fetch", "origin", branch, print_cmd=True)
bash("git", "checkout", branch, print_cmd=True)

