#!/usr/bin/env python3
import argparse
import re
from ast import List
import json
import os
import sys
from workflow_py.utils import bash_txt

from workflow_py.utils import fzf_select_multiple, fzf_select_one

sys.path.append(os.environ.get("WORKFLOW_PATH"))

parser = argparse.ArgumentParser(description="Select and output a ticket number for a commit/branch")
parser.add_argument("hint", nargs="?", type=str, help="a string that may be used to nickname the selected ticket (if exists will be auto-selected)")
args = parser.parse_args()

filepath="/home/rswanson/.ticketnames.txt"

branch = str(bash_txt("b"))
match = re.match(r"(\w*/)?([A-Z]{3,6}-\d{1,6})[^A-Z].*", branch)
if match is not None:
    branch_ticket = match.group(2)
    print(branch_ticket)
else:
    data = open(filepath, "r").read()
    tickets = json.loads(data)
    desc_list = [f"{ticket}: {desc}" for ticket, desc in tickets]
    selection = fzf_select_multiple(desc_list, min_required=0, max_allowed=1)

    if len(selection) == 0:
        ticket = input("Input new ticket: ")
        desc = input(f"Input description for {ticket}: ")
        tickets = [(ticket, desc)]+tickets
        with open(filepath, "w") as f:
            f.write(json.dumps(tickets, indent=4))
        print(f"\n{ticket}")
    else:
        ticket = selection[0].split(":")[0].strip()

    print(ticket)
