#!/bin/bash

git ls-files -m

MSG="$*"
if [[ "$MSG" == "" ]]; then
    read -p "Commit message: "
    MSG=$REPLY
fi
add && echo "Committing..." &&  git commit -m "$MSG" > /dev/null
if [ "$?" != 0 ]; then
    echo " ======================== COMMIT FALIED! ========================"
    exit 1
else
    push > /dev/null && echo "Push Complete" #&& check
fi
