#!/bin/bash
set -e
clear

TEST_DIR=$1
ATTEMPTS=$2
HOST=robertswanson@opuscydvux0351

mkdir -p $TEST_DIR
echo "Saving tests to $TEST_DIR"

if [ "$ATTEMPTS" == "" ]; then
    ATTEMPTS=1
fi

hostfree $HOST --ask

echo "Stopping all ctbv instances"
ssh $HOST "stopctbv"

echo "Synching sonic_conf"
sendconfig $HOST


BIN_DIR=~/dev/ctbv-bins/
echo "Sending binaries from $BIN_DIR"
scp $BIN_DIR/ctbv-master $HOST:~/ctbv-master > /dev/null
scp $BIN_DIR/ctbv-poc $HOST:~/ctbv-poc > /dev/null

run-ctbv-latency-tests-parallel threads p 5 $TEST_DIR $ATTEMPTS
run-ctbv-latency-tests-parallel threads m 1 $TEST_DIR $ATTEMPTS
run-ctbv-latency-tests-parallel threads p 1 $TEST_DIR $ATTEMPTS

#tryntimes $ATTEMPTS ctbv-latency-test m 1 1 $TEST_DIR $HOST --skip-verify-free --dont-sync-config --dont-sync-bins --dont-kill-other-ctbvs


echo "All tests completed succesfully"
