#!/usr/bin/env python3
import os
import sys

sys.path.append(os.environ.get("WORKFLOW_PATH"))
import argparse
import os
import shutil
import sys

from workflow_py.path_object.script.local_script_utils import get_local_script
from workflow_py.path_object.script.saved_script_utils import get_saved_script
from workflow_py.var_store import VAR_STORE

from workflow_py.utils import bash

parser = argparse.ArgumentParser(description="Edit local script then sync to saved scripts")
parser.add_argument("name", type=str, help="name of script to edit")
parser.add_argument("category", nargs="?", type=str, help="category to edit (required if script name is ambiguous across categories)")
args = parser.parse_args()

saved_script, category = get_saved_script(args.name, args.category)
try:
    local_script = get_local_script(args.name)
except FileNotFoundError:
    local_script = saved_script.write_to_dir(VAR_STORE.get_local_scripts_dir())

bash("vim", saved_script.path)
shutil.copy(saved_script.path, local_script.path)
print(f"Saved to {category.name}")
