#!/usr/bin/env python3
import os
import shutil
import sys

sys.path.append(os.environ.get("WORKFLOW_PATH"))

from py.bash import bash
from py.var_store import VAR_STORE

args = sys.argv

if len(args) == 2:
    name = args[1]
    category_name = None
elif len(args) == 3:
    name = args[1]
    category_name = args[2]
else:
    raise ValueError("Invalid number of arguments, usage: edit <name> [category_name]")

local_script = VAR_STORE.get_local_script(name)
saved_script, category = VAR_STORE.get_saved_script(name)

bash("vim", local_script.path)
print(f"Saving to {category.name}")
shutil.copy(local_script.path, saved_script.path)
