#!/usr/bin/env python3
import importlib.util
import os
import sys

sys.path.append(os.environ.get("WORKFLOW_PATH"))
from py.var_store import VAR_STORE

path = VAR_STORE.get_host_dir() / "pusher.py"
assert path.is_file(), f"Pusher script not found at {path}"
module_name = path.stem
module_spec = importlib.util.spec_from_file_location(module_name, path)
module = importlib.util.module_from_spec(module_spec)
module_spec.loader.exec_module(module)
module.push_to_saved()
