#!/usr/bin/env python3
import argparse
import os
import sys

sys.path.append(os.environ.get("WORKFLOW_PATH"))

from py.path_object.category.category_utils import get_host_categories, get_category_with_name

parser = argparse.ArgumentParser(description="List categories or scripts in a category")
parser.add_argument("-a", "--list-all", default=False, action="store_true", help="lists all categories, even those ignored by this host")
parser.add_argument("category", nargs="?", type=str, help="category to list scripts from")
args = parser.parse_args()

if args.category:
    category = get_category_with_name(args.category)
    script_names = [script.name for script in category.get_saved_scripts()]
    print(' '.join(script_names))
else:
    category_names = [category.name for category in get_host_categories(get_all=args.list_all)]
    print(' '.join(category_names));
