#!/usr/bin/env python3
import argparse
import os
import sys

sys.path.append(os.environ.get("WORKFLOW_PATH"))

from workflow_py.var_store import VAR_STORE

parser = argparse.ArgumentParser(description="List categories or scripts in a category")
parser.add_argument("-a", "--list-all", help="lists all categories, even those ignored by this host", action="store_true")
parser.add_argument("category", nargs="?", type=str, help="category to list scripts from")
args = parser.parse_args()


if args.category:
    print(VAR_STORE.catego(args.category).get_script_names())
else:
    print(VAR_STORE.get_host_categories(get_all=args.list_all))
