#!/usr/bin/env python3
import argparse
import os
import sys

sys.path.append(os.environ.get("WORKFLOW_PATH"))
from workflow_py.path_object.category.category_utils import make_category_with_name

parser = argparse.ArgumentParser(description="Create a new category")
parser.add_argument("name", type=str, help="name of the new category")
args = parser.parse_args()

category_name = args.name
category = make_category_with_name(category_name)
print("Created category", category.name)
