#!/usr/bin/env python3
import os
import sys

sys.path.append(os.environ.get("WORKFLOW_PATH"))
import argparse
import os
import shutil
import sys

from py.path_object.script.local_script_utils import get_local_script
from py.path_object.script.saved_script_utils import get_saved_script

sys.path.append(os.environ.get("WORKFLOW_PATH"))

from py.bash import bash

parser = argparse.ArgumentParser(description="Edit local script then sync to saved scripts")
parser.add_argument("name", type=str, help="name of script to edit")
parser.add_argument("category", nargs="?", type=str, help="category to edit (required if script name is ambiguous across categories)")
args = parser.parse_args()

local_script = get_local_script(args.name)
saved_script, category = get_saved_script(args.name, args.category)

bash("vim", local_script.path)
print(f"Saving to {category.name}")
shutil.copy(local_script.path, saved_script.path)



# if [ "$2" == "" ]
# then
# CAT="misc"
# else
# CAT=$2
# fi
#
# vim ~/scripts/$1 && chmod +x ~/scripts/$1 && cp ~/scripts/$1 ~/workflow/scripts/$CAT
