#!/usr/bin/env python3
import argparse
import os
import shutil
import sys

sys.path.append(os.environ.get("WORKFLOW_PATH"))

from py.var_store import VAR_STORE
from py.path_object.script.local_script_utils import get_local_script
from py.path_object.script.saved_script_utils import get_saved_script, validate_script_name_available

parser = argparse.ArgumentParser(description="Rename a script")
parser.add_argument("old_name", type=str, help="name of script to edit")
parser.add_argument("new_name", type=str, help="name of script to edit")
parser.add_argument("-c", "--category", default=None, type=str, help="category of script (required if script name is ambiguous across categories)")
args = parser.parse_args()

saved_script, category = get_saved_script(args.old_name, args.category)
local_script = get_local_script(args.old_name)
validate_script_name_available(args.new_name)

shutil.move(saved_script.path, category.path / args.new_name)
shutil.move(local_script.path, VAR_STORE.get_local_scripts_dir() / args.new_name)
print(f"Renamed {args.old_name} to {args.new_name} in category {category.name}")
