#!/usr/bin/env python3
import argparse
import os
import sys

sys.path.append(os.environ.get("WORKFLOW_PATH"))

parser = argparse.ArgumentParser(description="XXXXX")
parser.add_argument("-f", "--flag", action="store_true", help="XXXXX")
parser.add_argument("optional", nargs="?", type=str, help="XXXXX")
parser.add_argument("-l", "--list", nargs="+", type=str, help="XXXXX")
parser.add_argument("-c", "--choice", choices=["a", "b", "c"], help="XXXXX")
args = parser.parse_args()



