#!/usr/bin/env python3
import argparse
import os
import sys

from workflow_py.path_object.script.saved_script_utils import choose_template
from workflow_py.utils import bash

sys.path.append(os.environ.get("WORKFLOW_PATH"))

template = choose_template()
bash("vim", template)
