#!/usr/bin/env python3
import argparse
import os
import sys
from typing import List

from workflow_py.utils import fzf_select_one
from workflow_py.var_store import VAR_STORE

sys.path.append(os.environ.get("WORKFLOW_PATH"))
from workflow_py.path_object.category.category_utils import make_category_with_name, get_host_categories

parser = argparse.ArgumentParser(description="Create a new category")
parser.add_argument("name", type=str, nargs="?", help="name of the new category")
args = parser.parse_args()

if args.name:
    category_name = args.name
else:
    parent_categories: List[str] = ["/"] + [f"/{c.name}" for c in get_host_categories()]
    parent_category = fzf_select_one(parent_categories, prompt="Choose parent category")
    chosen_name = input(f"Name for new sub-category of '{parent_category}': ")
    category_name = f"{parent_category}/{chosen_name}"

category = make_category_with_name(category_name)
print("Created category", category.name)
