#!/usr/bin/env python3
import os
import sys
sys.path.append(os.environ.get("WORKFLOW_PATH"))
from workflow_py.base_objects.puller import host_pull_to_local

sys.path.append(os.environ.get("WORKFLOW_PATH"))

host_pull_to_local()
