#!/usr/bin/env python3
import os
import sys
sys.path.append(os.environ.get("WORKFLOW_PATH"))

from workflow_py.base_objects.pusher import host_push_to_saved

sys.path.append(os.environ.get("WORKFLOW_PATH"))

host_push_to_saved()
