#!/bin/bash

HOST=$1
ASK_TO_FAIL=$2

if [ "$HOST" == "" ]; then
    HOST=robertswanson@opuscydvux0350
fi

if [ "$(ssh $HOST 'w | grep -v robertsw | wc -l')" != "2" ]; then
    echo "Jump host $HOST is being used"
    echo "$(ssh $HOST 'w | grep -v robertsw')"
    if [ "$ASK_TO_FAIL" == "--ask" ]; then
        read -p "Do you want to continue? [y/N] " -n 1 -r
        if ! [[ $REPLY =~ ^[Yy]$ ]]; then
            echo
            exit 100
        fi
        echo
    fi
elif [ "$ASK_TO_FAIL" != "--ask" ]; then
    echo "Host $HOST is free"
fi
