#!/bin/bash
set -e
set -o xtrace
TEST_NAME=$1
DEST_DIR=~/inbox/$TEST_NAME
SRC_DIR="~/dev/perf/test_results"

FILES="perf.svg perf.collapsed satnet1_perf.pdf satnet1_kallsyms satnet1_perf.data perf.script"

mkdir -p $DEST_DIR

for file in $FILES; do
    scp rswanson@rswanson-z4l:$SRC_DIR/$file $DEST_DIR/$file
done

